# Generated by Django 2.0.6 on 2018-07-01 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Adjunto', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Iva', models.IntegerField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Contrato', models.ForeignKey(blank='false', null='false', on_delete=django.db.models.deletion.CASCADE, to='Gestion.Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Publicada', models.BooleanField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='Licitacion',
            field=models.ForeignKey(blank='false', null='false', on_delete=django.db.models.deletion.CASCADE, to='Gestion.Licitacion'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='Licitacion',
            field=models.ForeignKey(blank='false', null='false', on_delete=django.db.models.deletion.CASCADE, to='Gestion.Licitacion'),
        ),
    ]
