# Generated by Django 2.0.6 on 2018-07-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='Publicada',
            field=models.BooleanField(choices=[('S', 'Si'), ('N', 'No')], max_length=1),
        ),
    ]
