# Generated by Django 2.0.6 on 2018-07-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_auto_20180701_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='Publicada',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default='No', max_length=1),
        ),
    ]
