# Generated by Django 2.0.6 on 2018-07-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_auto_20180701_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='Fecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='Licitacion',
            new_name='licitacion',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='Adjunto',
            new_name='adjunto',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='Contrato',
            new_name='contrato',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='Fecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='Iva',
            new_name='iva',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='Licitacion',
            new_name='licitacion',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='Precio',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='Total',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='licitacion',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='licitacion',
            old_name='Publicada',
            new_name='publicada',
        ),
    ]
